Young5097/eDrink24-server

src/main/java/org/eDrink24/config/CustomerMapper.java
src/main/java/org/eDrink24/dto/customer/CustomerDTO.java
src/main/java/org/eDrink24/service/customer/CustomerService.java
src/main/java/org/eDrink24/service/customer/CustomerServiceImpl.java
src/main/resources/application.properties
src/main/resources/config/CustomerMapper.xml

- controller/customer/CustomerMyPageController.java
회원정보를 로그인아이디로 조회

feat 마이페이지 회원정보 조회기능

---

src/main/java/org/eDrink24/config/CustomerMapper.java
src/main/java/org/eDrink24/controller/mypage/UpdateMyPageCustomerController.java
src/main/java/org/eDrink24/service/customer/CustomerService.java
src/main/java/org/eDrink24/service/customer/CustomerServiceImpl.java
src/main/resources/application.properties
src/main/resources/config/CustomerMapper.xml

마이페이지 회원정보 중에 패스워드, 휴대폰 번호, 이메일, 주소 변경 가능하게 구현
그 중에서 패스워드는 수정하면 DB에 암호화해서 저장되도록 함.

Feature 마이페이지 회원정보 수정

---

src/main/java/org/eDrink24/config/ProductMapper.java
src/main/java/org/eDrink24/controller/mypage/UpdateMyPageCustomerController.java
src/main/java/org/eDrink24/controller/product/ProductController.java
src/main/java/org/eDrink24/dto/product/ProductDTO.java
src/main/java/org/eDrink24/service/product/ProductService.java
src/main/java/org/eDrink24/service/product/ProductServiceImpl.java
src/main/resources/config/ProductMapper.xml

제품 전체 목록을 보여주는 기능을 ProductController에 구현
그리고 마이페이지 UpdateMyPageCustomerController에 어떤 기능하는건지 주석 추가

Feature02 제품목록 페이지 기능

---

src/main/java/org/eDrink24/config/ProductMapper.java
src/main/java/org/eDrink24/controller/product/ProductController.java
src/main/java/org/eDrink24/service/product/ProductService.java
src/main/java/org/eDrink24/service/product/ProductServiceImpl.java
src/main/resources/config/ProductMapper.xml

category1에 해당하는 제품 보여주는 기능 구현
- org.eDrink24.controller.product.ProductController.java 
- 주석으로 어떤 기능인지 구분해놨음.

feat03 제품목록 페이지 기능2

---

src/main/java/org/eDrink24/config/ProductMapper.java
src/main/java/org/eDrink24/controller/product/ProductController.java
src/main/java/org/eDrink24/dto/product/ProductDTO.java
src/main/java/org/eDrink24/service/product/ProductService.java
src/main/java/org/eDrink24/service/product/ProductServiceImpl.java
src/main/resources/application.properties
src/main/resources/config/ProductMapper.xml

기본순(producId 오름차순), 높은 가격순, 낮은 가격순, 찜순, 평점순 정렬
- org.eDrink24.controller.product.ProductController.java 주석으로 구분해놨음

feat 제품목록 필터링 기능

---

src/main/java/org/eDrink24/config/ProductMapper.java
src/main/java/org/eDrink24/controller/product/ProductController.java
src/main/java/org/eDrink24/service/product/ProductService.java
src/main/java/org/eDrink24/service/product/ProductServiceImpl.java
src/main/resources/config/ProductMapper.xml

- category2에 해당하는 제품 보여주는 기능 구현
- org.eDrink24.controller.product.ProductController.java
- 주석으로 구분해놨음

Feature04 제품목록페이지 기능 구현3

---

src/main/java/org/eDrink24/controller/product/ProductController.java
src/main/resources/config/ProductMapper.xml

ProductController.java      filterProduct  파라미터명 변경
ProductMapper.xml          filterProduct  파라미터명 변경 및 주석 추가

fix 제품목록 필터링 기능 주석 추가

---

src/main/java/org/eDrink24/controller/product/ProductController.java

fix ProductController

---

src/main/java/org/eDrink24/config/ProductMapper.java
src/main/java/org/eDrink24/controller/product/DetailProductController.java
src/main/java/org/eDrink24/controller/product/ProductController.java
src/main/java/org/eDrink24/dto/product/DetailProductDTO.java
src/main/java/org/eDrink24/service/product/ProductService.java
src/main/java/org/eDrink24/service/product/ProductServiceImpl.java
src/main/resources/config/ProductMapper.xml

제품 이미지 클릭 시 제품 상세 설명 페이지로 넘어가는 기능 구현
Product 와 ProductImage 테이블 조인 사용
- org/eDrink24/dto/product/DetailProductDTO.java
- org/eDrink24/controller/product/DetailProductController.java

feat 제품상세페이지 기능

---

src/main/java/org/eDrink24/config/CustomerMapper.java
src/main/java/org/eDrink24/controller/customer/CustomerController.java
src/main/java/org/eDrink24/service/customer/CustomerService.java
src/main/java/org/eDrink24/service/customer/CustomerServiceImpl.java
src/main/resources/config/CustomerMapper.xml

회원가입 시에 아이디가 중복되면 409에러 발생하고 "이 아이디는 사용불가합니다." 메세지 띄우고, 
아이디가 사용가능하면 "이 아이디는 사용가능합니다." 메세지를 띄운다.

feat 회원가입 시 아이디 중복체크 기능

---

src/main/java/org/eDrink24/config/OrderMapper.java
src/main/java/org/eDrink24/controller/order/OrderController.java
src/main/java/org/eDrink24/dto/basket/BasketDTO.java
src/main/java/org/eDrink24/dto/order/OrderDTO.java
src/main/java/org/eDrink24/dto/product/ProductDTO.java
src/main/java/org/eDrink24/service/order/OrderService.java
src/main/java/org/eDrink24/service/order/OrderServiceImpl.java
src/main/java/org/eDrink24/service/product/ProductService.java
src/main/java/org/eDrink24/service/product/ProductServiceImpl.java
src/main/resources/config/OrderMapper.xml

장바구니에 담긴 상품 목록 불러오기
결제하기(ORDERS 테이블에 저장)

feat 주문페이지 기능

---

src/main/java/org/eDrink24/config/BasketMapper.java
src/main/java/org/eDrink24/config/CustomerMapper.java
src/main/java/org/eDrink24/controller/basket/BasketController.java
src/main/java/org/eDrink24/controller/customer/CustomerController.java
src/main/java/org/eDrink24/dto/basket/BaksetDTO.java
src/main/java/org/eDrink24/dto/basket/BasketJoinProductDTO.java
src/main/java/org/eDrink24/dto/product/ProductDTO.java
src/main/java/org/eDrink24/service/basket/BasketService.java
src/main/java/org/eDrink24/service/basket/BasketServiceImpl.java
src/main/java/org/eDrink24/service/customer/CustomerService.java
src/main/java/org/eDrink24/service/customer/CustomerServiceImpl.java
src/main/resources/config/BasketMapper.xml
src/main/resources/config/CustomerMapper.xml

로그인 후 장바구니 버튼 클릭 시에 bakset테이블에 userId, productId, basketQuantity 저장
- BasketDTO 사용
장바구니 페이지에서 userId를 기준으로 장바구니에 담은 목록 보여줌
- BasketJoinProductDTO 사용

feat 장바구니 기능

---

src/main/java/org/eDrink24/config/BasketMapper.java
src/main/java/org/eDrink24/controller/basket/BasketController.java
src/main/java/org/eDrink24/service/basket/BasketService.java
src/main/java/org/eDrink24/service/basket/BasketServiceImpl.java
src/main/resources/config/BasketMapper.xml

feat 장바구니 삭제 기능 구현

---

src/main/java/org/eDrink24/EDrink24ServerApplication.java
src/main/java/org/eDrink24/config/OrderMapper.java
src/main/java/org/eDrink24/controller/order/OrderController.java
src/main/java/org/eDrink24/service/order/OrderService.java
src/main/java/org/eDrink24/service/order/OrderServiceImpl.java
src/main/resources/config/OrderMapper.xml

장바구니 목록 전체조회 -> 아이디별 조회로 수정
xml 쿼리문 where절 추가
@PathVariable Integer userId 추가

fix showAllBaket

---

src/main/java/org/eDrink24/config/BasketMapper.java
src/main/java/org/eDrink24/controller/basket/BasketController.java
src/main/java/org/eDrink24/service/basket/BasketService.java
src/main/java/org/eDrink24/service/basket/BasketServiceImpl.java
src/main/resources/config/BasketMapper.xml

feat 장바구니 선택 목록 삭제 기능 구현
- 이전 모든 목록 삭제는 회원별로 모든 목록이 삭제되지 않았는데, 회원별로 모든 목록이 삭제되도록 수정함.
- 장바구니 회원별로 선택한 목록만 삭제 가능하도록 구현함.

fix 장바구니 모든 목록 삭제 기능 수정

---

src/main/java/org/eDrink24/config/BasketMapper.java
src/main/java/org/eDrink24/controller/basket/BasketController.java
src/main/java/org/eDrink24/service/basket/BasketService.java
src/main/java/org/eDrink24/service/basket/BasketServiceImpl.java
src/main/resources/config/BasketMapper.xml

- 원래 userId를 @pathVariable로 이용했는데 
React와 연동하면서 login했을 때 장바구니를 확인할 수 있어서 
Mapper에 서브쿼리를 사용하여 loginId가 @pathVariable로 이용되게 수정
- 목록 선택해서 삭제하기는 아직 수정중

fix3 장바구니 기능 수정

---

src/main/java/org/eDrink24/controller/mypage/UpdateMyPageCustomerController.java
src/main/java/org/eDrink24/domain/customer/Customer.java
src/main/java/org/eDrink24/dto/customer/CustomerDTO.java
src/main/resources/config/CustomerMapper.xml

- UpdateMyPageCustomerController.java
- updateCustomer() 추가
- CustomerMapper 및 CustomerDTO
- userId(PK)도 가져오도록 수정

feat : 회원정보수정 JPA버전 추가 및 회원정보 호출 매퍼수정

---

src/main/java/org/eDrink24/config/BasketMapper.java
src/main/java/org/eDrink24/config/OrderMapper.java
src/main/java/org/eDrink24/controller/basket/BasketController.java
src/main/java/org/eDrink24/controller/order/OrderController.java
src/main/java/org/eDrink24/service/basket/BasketService.java
src/main/java/org/eDrink24/service/basket/BasketServiceImpl.java
src/main/java/org/eDrink24/service/order/OrderService.java
src/main/java/org/eDrink24/service/order/OrderServiceImpl.java
src/main/resources/config/BasketMapper.xml
src/main/resources/config/OrderMapper.xml

- 장바구니 목록 중 선택된 목록만 삭제하는 코드 중 loginId에 맞는 userId를 찾고 장바구니Id로 삭제하는 SQL문에서 parameterType을 string에서 map으로 수정함. 이유는 BasketMapper.xml에 주석으로 추가
- 주문페이지에서 loginId에 맞는 userId를 찾기위해서 OrderMapper.xml에 서브쿼리를 사용하고 parameterType을 String loginId를 사용

fix4 장바구니 기능 수정 및 주문페이지 수정

---

src/main/java/org/eDrink24/config/CouponMapper.java
src/main/java/org/eDrink24/config/DibMapper.java
src/main/java/org/eDrink24/config/StoreMapper.java
src/main/java/org/eDrink24/controller/coupon/CouponController.java
src/main/java/org/eDrink24/controller/dibs/DibController.java
src/main/java/org/eDrink24/controller/store/StoreController.java
src/main/java/org/eDrink24/dto/coupon/CouponDTO.java
src/main/java/org/eDrink24/dto/dibs/DibDTO.java
src/main/java/org/eDrink24/dto/store/StoreDTO.java
src/main/java/org/eDrink24/service/coupon/CouponService.java
src/main/java/org/eDrink24/service/coupon/CouponServiceImpl.java
src/main/java/org/eDrink24/service/dibs/DibService.java
src/main/java/org/eDrink24/service/dibs/DibServiceImpl.java
src/main/java/org/eDrink24/service/store/StoreService.java
src/main/java/org/eDrink24/service/store/StoreServiceImpl.java
src/main/resources/config/CouponMapper.xml
src/main/resources/config/DibMapper.xml
src/main/resources/config/OrderMapper.xml
src/main/resources/config/StoreMapper.xml

쿠폰 목록 select, 찜 목록 insert 및 select 기능

feat 쿠폰 조회, 찜목록 추가/조회

---

src/main/java/org/eDrink24/controller/product/ProductController.java
src/main/java/org/eDrink24/dto/product/ProductDTO.java
src/main/resources/config/ProductMapper.xml

- 신상품순으로 나오는지 확인해보기 위해서  ProductMapper.xml에 enrollDate 추가
- ProductController에서 category1,category2에 따라 제품 목록 보여주는 코드에 URL 수정
- ProductDTO에 productId 추가
- 제품상세페이지에 productId가 필요해서 ProductMapper.xml 모든 SQL문에 productId 추가

fix5 제품목록페이지 수정

---

src/main/java/org/eDrink24/controller/message/MessageSmsController.java
src/main/java/org/eDrink24/controller/mypage/UpdateMyPageCustomerController.java
src/main/java/org/eDrink24/repository/customer/CustomerRepository.java
src/main/java/org/eDrink24/repository/message/MessageSmsRepository.java
src/main/java/org/eDrink24/service/customer/CustomerService.java
src/main/java/org/eDrink24/service/customer/CustomerServiceImpl.java
src/main/java/org/eDrink24/service/message/MessageSmsService.java
src/main/java/org/eDrink24/service/message/MessageSmsServiceImpl.java

- MessageSmsService.isUsedPhoneNum
- 가입여부 확인후, 가입되어있으면 BAD_REQUEST 응답
- 안되어있으면 OK 응답

feat : sms인증시 가입여부확인

---

src/main/java/org/eDrink24/controller/message/MessageSmsController.java
src/main/java/org/eDrink24/service/message/MessageSmsServiceImpl.java

- 생성자 패턴 => builder 패턴으로 변경
- client에서 편하게 처리하도록 상태메세지 수정

fix : status 메세지 수정

---

src/main/java/org/eDrink24/config/BasketMapper.java
src/main/java/org/eDrink24/controller/basket/BasketController.java
src/main/java/org/eDrink24/controller/login/JwtAuthenticationController.java
src/main/java/org/eDrink24/dto/basket/BasketDTO.java
src/main/java/org/eDrink24/service/basket/BasketService.java
src/main/java/org/eDrink24/service/basket/BasketServiceImpl.java
src/main/resources/application.properties
src/main/resources/config/BasketMapper.xml

- basket 테이블에 저장하기 위해 userId가 필요한데 자바스크립트에서 우리가 가지고 있는건 loginId밖에 없었음.
- userId를 쓰기 위해서 BasketMapper.xml에 userId를 가져오는 select문을 추가하고
BasketController.java
saveProductToBasket 메소드에서 loginId에 맞는 userId를 BasketDTO에 저장하는 코드 작성

fix6 장바구니 기능 수정

---

src/main/java/org/eDrink24/controller/basket/BasketController.java
src/main/java/org/eDrink24/controller/customer/CustomerController.java
src/main/java/org/eDrink24/controller/login/JwtAuthenticationController.java
src/main/java/org/eDrink24/controller/mypage/MypageCustomerController.java
src/main/java/org/eDrink24/service/customer/CustomerService.java
src/main/java/org/eDrink24/service/customer/CustomerServiceImpl.java

- userId가 클라이언트에서 필요한 일이 많음
- token 보낼때 userId도 response에 Map에 담아서 보내도록 변경

[fix] JwtAuthenticationController 수정
